[[constraint]]
  branch = "master"
  name = "github.com/howeyc/crc16"

[[constraint]]
  branch = "master"
  name = "github.com/osamingo/indigo"

[[constraint]]
  branch = "master"
  name = "github.com/pkg/errors"

[[constraint]]
  branch = "master"
  name = "google.golang.org/appengine"

[[constraint]]
  name = "gopkg.in/go-playground/validator.v9"
  version = "9.7.0"
